name: 'gb_case_2'
version: '1.0.0'
config-version: 2

profile: 'gb_case_2'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gb_case_2:
    staging:
      +materialized: view
    marts:
      +materialized: table
    
