gb_case_2:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /usr/local/airflow/gcloud/dbt/credentials.json
      project: dh-dev-357120
      dataset: dev
      threads: 1
      location: us-east4