SELECT    SUM(QTD_VENDA) AS TOTAL_SALES,
          CAST(EXTRACT(YEAR FROM DATA_VENDA) AS string) AS YEAR,
          LPAD(CAST(EXTRACT(MONTH FROM DATA_VENDA) AS string),2,'0') AS MONTH
FROM      `base_vendas_dataset.base_vendas`
GROUP BY  2,3
ORDER BY  YEAR DESC, MONTH DESC